In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from nltk.corpus import stopwords
from nltk.tokenize import wordpunct_tokenize
from nltk.stem import *
from scipy.stats import pearsonr
from sklearn.preprocessing import MinMaxScaler

In [2]:
manga = pd.read_json('data/raw/manga.json')

In [3]:
manga.shape

(80657, 30)

In [4]:
old_size = manga.shape[0]
manga = manga.drop_duplicates(subset=['mal_id']).reset_index(drop=True)
print('Duplicates:', old_size - manga.shape[0])

Duplicates: 244

In [5]:
manga.head(10)

,mal_id,url,images,approved,titles,title,title_english,title_japanese,title_synonyms,type,...,members,favorites,synopsis,background,authors,serializations,genres,explicit_genres,themes,demographics
0,142469,https://myanimelist.net/manga/142469/Daija_ni_...,{'jpg': {'image_url': 'https://cdn.myanimelist...,True,"[{'type': 'Default', 'title': 'Daija ni Totsui...",Daija ni Totsuida Musume,The Great Snake's Bride,大蛇に嫁いだ娘,[The Girl Who Married the Big Snake],Manga,...,2335,15,"For five hundred years, a giant snake god has ...",Daija ni Totsuida Musume is as a web manga rel...,"[{'mal_id': 56083, 'type': 'people', 'name': '...","[{'mal_id': 1643, 'type': 'manga', 'name': 'Co...","[{'mal_id': 22, 'type': 'manga', 'name': 'Roma...",[],[],[]
1,142471,https://myanimelist.net/manga/142471/Majo_no_Yu,{'jpg': {'image_url': 'https://cdn.myanimelist...,True,"[{'type': 'Default', 'title': 'Majo no Yu'}, {...",Majo no Yu,Witch's Hot Spring,魔女ノ湯,[],Manga,...,107,0,"Sawa, a salaryman working for a black company,...",,"[{'mal_id': 12134, 'type': 'people', 'name': '...","[{'mal_id': 451, 'type': 'manga', 'name': 'You...","[{'mal_id': 7, 'type': 'manga', 'name': 'Myste...",[],[],"[{'mal_id': 41, 'type': 'manga', 'name': 'Sein..."
2,142472,https://myanimelist.net/manga/142472/Ie_kara_N...,{'jpg': {'image_url': 'https://cdn.myanimelist...,True,"[{'type': 'Default', 'title': 'Ie kara Nigedas...","Ie kara Nigedashitai Watashi ga, Ukkari Akogar...",None,家から逃げ出したい私が、うっかり憧れの大魔法使い様を買ってしまったら,[That Time I Bought a Great Wizard in Hopes of...,Manga,...,327,1,"Giselle, after finding out that she's to be ma...",,"[{'mal_id': 52744, 'type': 'people', 'name': '...","[{'mal_id': 419, 'type': 'manga', 'name': 'Gan...","[{'mal_id': 10, 'type': 'manga', 'name': 'Fant...",[],[],[]
3,142473,https://myanimelist.net/manga/142473/Natsu_no_Su,{'jpg': {'image_url': 'https://cdn.myanimelist...,True,"[{'type': 'Default', 'title': 'Natsu no Su'}, ...",Natsu no Su,None,夏の巣,"[Yuragi, Niku Asobi, Koniwa, Sayaguchi-sensei ...",Manga,...,34,0,1. Yuragi\n2. Niku Asobi\n3-4. Koniwa\n5. Saya...,,"[{'mal_id': 13247, 'type': 'people', 'name': '...","[{'mal_id': 258, 'type': 'manga', 'name': 'Com...","[{'mal_id': 12, 'type': 'manga', 'name': 'Hent...",[],[],[]
4,142475,https://myanimelist.net/manga/142475/Kishibe_R...,{'jpg': {'image_url': 'https://cdn.myanimelist...,True,"[{'type': 'Default', 'title': 'Kishibe Rohan T...",Kishibe Rohan Tanpen Shousetsushuu,None,岸辺露伴 短編小説集,"[Kishibe Rohan wa Sakebanai, Rohan Kishibe Doe...",Light Novel,...,324,1,Kishibe Rohan Tanpen Shousetsushuu is an antho...,,"[{'mal_id': 35997, 'type': 'people', 'name': '...","[{'mal_id': 25, 'type': 'manga', 'name': 'Ultr...","[{'mal_id': 7, 'type': 'manga', 'name': 'Myste...",[],[],"[{'mal_id': 41, 'type': 'manga', 'name': 'Sein..."
5,142477,https://myanimelist.net/manga/142477/Jingai_no...,{'jpg': {'image_url': 'https://cdn.myanimelist...,True,"[{'type': 'Default', 'title': 'Jingai no Eroho...",Jingai no Erohon: Scylla no Maki,None,人外のエロ本 スキュラの巻,[],Doujinshi,...,27,0,None,None,"[{'mal_id': 54877, 'type': 'people', 'name': '...",[],"[{'mal_id': 10, 'type': 'manga', 'name': 'Fant...",[],[],[]
6,142478,https://myanimelist.net/manga/142478/Seigangu_...,{'jpg': {'image_url': 'https://cdn.myanimelist...,True,"[{'type': 'Default', 'title': 'Seigangu Keikak...",Seigangu Keikaku: Namaiki na Otouto wo Fukujuu...,None,性玩具計画 生意気な弟を服従させたくて,[],Doujinshi,...,44,0,None,None,"[{'mal_id': 54877, 'type': 'people', 'name': '...",[],"[{'mal_id': 12, 'type': 'manga', 'name': 'Hent...",[],[],[]
7,142480,https://myanimelist.net/manga/142480/Hide_and_...,{'jpg': {'image_url': 'https://cdn.myanimelist...,True,"[{'type': 'Default', 'title': 'Hide and Heat'}...",Hide and Heat,None,Hide and Heat,[],One-shot,...,368,2,None,None,"[{'mal_id': 54434, 'type': 'people', 'name': '...","[{'mal_id': 983, 'type': 'manga', 'name': 'Com...","[{'mal_id': 12, 'type': 'manga', 'name': 'Hent...",[],[],[]
8,142483,https://myanimelist.net/manga/142483/Shinobu_K...,{'jpg': {'image_url': 'https://cdn.myanimelist...,True,"[{'type': 'Default', 'title': 'Shinobu Koi hod...",Shinobu Koi hodo: Sukisugiru Dannasama ni Deki...,To Ninja Love Is to Ninja Live: Is the Man I L...,忍ぶ恋ほど －好きすぎる旦那さまに溺愛されてます？－,[],Manga,...,207,0,"Ayame is a ninja-in-training, known among her ...",Shinobu Koi hodo: Sukisugiru Dannasama ni Deki...,"[{'mal_id': 50007, 'type': 'people', 'name': '...","[{'mal_id': 1440, 'type': 'manga', 'name': 'Lo...","[{'mal_id': 49, 'type': 'manga', 'name': 'Erot...",[],[],"[{'mal_id': 42, 'type': 'manga', 'name': 'Jose..."
9,142488,https://myanimelist.net/manga/142488/Hetare_Ma...,{'jpg': {'image_url': 'https://cdn.myanimelist...,True,"[{'type': 'Default', 'title': 'Hetare Maou to ...",Hetare Maou to Tsundere Yuusha,Wimpy Demon King and Tsundere Hero,ヘタレ魔王とツンデレ勇者,[He Is a Favorite of the Satan],Manga,...,872,1,In order to defeat the Demon King of Mano who ...,,"[{'mal_id': 20188, 'type': 'people', 'name': '...","[{'mal_id': 1491, 'type': 'manga', 'name': 'eq...","[{'mal_id': 28, 'type': 'manga', 'name': 'Boys...",[],"[{'mal_id': 6, 'type': 'manga', 'name': 'Mytho...",[]

In [6]:
manga.dtypes

mal_id               int64
url                 object
images              object
approved              bool
titles              object
title               object
title_english       object
title_japanese      object
title_synonyms      object
type                object
chapters           float64
volumes            float64
status              object
publishing            bool
published           object
score              float64
scored             float64
scored_by          float64
rank               float64
popularity           int64
members              int64
favorites            int64
synopsis            object
background          object
authors             object
serializations      object
genres              object
explicit_genres     object
themes              object
demographics        object
dtype: object

In [7]:
missing_per_col1 = manga.isna().sum()
print(missing_per_col1)

mal_id                 0
url                    0
images                 0
approved               0
titles                 0
title                  0
title_english      53449
title_japanese      1035
title_synonyms         0
type                   0
chapters           23771
volumes            24075
status                 0
publishing             0
published              0
score              51283
scored             51283
scored_by          51283
rank               24772
popularity             0
members                0
favorites              0
synopsis           23828
background         23828
authors                0
serializations         0
genres                 0
explicit_genres        0
themes                 0
demographics           0
dtype: int64

In [8]:
data=manga.sample(n=10000,random_state=42)

In [9]:
print(data.shape)

(10000, 30)

In [10]:
print(data.dtypes)

mal_id               int64
url                 object
images              object
approved              bool
titles              object
title               object
title_english       object
title_japanese      object
title_synonyms      object
type                object
chapters           float64
volumes            float64
status              object
publishing            bool
published           object
score              float64
scored             float64
scored_by          float64
rank               float64
popularity           int64
members              int64
favorites            int64
synopsis            object
background          object
authors             object
serializations      object
genres              object
explicit_genres     object
themes              object
demographics        object
dtype: object

In [11]:
data=data.drop(["demographics","url","images","approved","titles","title_english","title_japanese","title_synonyms","scored","authors","explicit_genres","themes","background","synopsis"],axis=1)

In [12]:
data.shape

(10000, 16)

In [13]:
data.dtypes

mal_id              int64
title              object
type               object
chapters          float64
volumes           float64
status             object
publishing           bool
published          object
score             float64
scored_by         float64
rank              float64
popularity          int64
members             int64
favorites           int64
serializations     object
genres             object
dtype: object

In [14]:
data.head(10)

,mal_id,title,type,chapters,volumes,status,publishing,published,score,scored_by,rank,popularity,members,favorites,serializations,genres
39083,136355,Hana Akari,Manga,8.0,1.0,Finished,False,"{'from': '2014-04-24T00:00:00+00:00', 'to': '2...",NaN,NaN,NaN,66813,48,0,"[{'mal_id': 1307, 'type': 'manga', 'name': 'Qp...","[{'mal_id': 28, 'type': 'manga', 'name': 'Boys..."
75058,163272,Futarigurashi no Otoriyose Biyori,Manga,NaN,NaN,Publishing,True,"{'from': '2023-04-24T00:00:00+00:00', 'to': No...",NaN,NaN,42132.0,74476,27,0,"[{'mal_id': 1537, 'type': 'manga', 'name': 'Sh...","[{'mal_id': 47, 'type': 'manga', 'name': 'Gour..."
32496,148128,Kaihatsu Buchou no Himitsu no Oshigoto,Manga,7.0,1.0,Finished,False,"{'from': '2017-10-06T00:00:00+00:00', 'to': '2...",NaN,NaN,NaN,57574,75,0,"[{'mal_id': 1524, 'type': 'manga', 'name': 'BO...","[{'mal_id': 28, 'type': 'manga', 'name': 'Boys..."
16431,41031,Kamakura Deco & Kofu Life,Manga,NaN,NaN,Publishing,True,"{'from': '2011-06-18T00:00:00+00:00', 'to': No...",NaN,NaN,39295.0,37677,223,2,"[{'mal_id': 741, 'type': 'manga', 'name': 'Alt...","[{'mal_id': 4, 'type': 'manga', 'name': 'Comed..."
59540,17490,First Time I Saw You,Manhwa,NaN,6.0,Finished,False,"{'from': '2000-01-01T00:00:00+00:00', 'to': No...",NaN,NaN,24314.0,67114,48,0,[],"[{'mal_id': 22, 'type': 'manga', 'name': 'Roma..."
35700,12683,Oishii Reikon no Tabekata,Manga,7.0,1.0,Finished,False,"{'from': '2001-03-01T00:00:00+00:00', 'to': '2...",NaN,NaN,23294.0,57711,74,0,"[{'mal_id': 286, 'type': 'manga', 'name': 'Ich...","[{'mal_id': 28, 'type': 'manga', 'name': 'Boys..."
22609,51257,Kamisama Drop,Manga,44.0,11.0,Finished,False,"{'from': '2012-12-06T00:00:00+00:00', 'to': '2...",6.92,713.0,10684.0,7301,3105,1,"[{'mal_id': 282, 'type': 'manga', 'name': 'Sho...","[{'mal_id': 22, 'type': 'manga', 'name': 'Roma..."
31264,63093,Sex Nochi Ryou Omoi,Manga,8.0,1.0,Finished,False,"{'from': '2012-04-24T00:00:00+00:00', 'to': '2...",7.04,346.0,NaN,17147,1008,4,"[{'mal_id': 495, 'type': 'manga', 'name': 'Com...","[{'mal_id': 12, 'type': 'manga', 'name': 'Hent..."
20975,165827,Cuddle: Juujin Omegaverse,Manga,NaN,NaN,Publishing,True,"{'from': '2023-04-11T00:00:00+00:00', 'to': No...",NaN,NaN,NaN,36523,240,0,[],"[{'mal_id': 28, 'type': 'manga', 'name': 'Boys..."
75011,108516,Sentimental: Aizome Gorou Sakuhinshuu,Manga,8.0,1.0,Finished,False,"{'from': '2005-06-10T00:00:00+00:00', 'to': '2...",NaN,NaN,37141.0,67301,47,0,"[{'mal_id': 451, 'type': 'manga', 'name': 'You...","[{'mal_id': 9, 'type': 'manga', 'name': 'Ecchi..."

In [15]:
data['published_from'] = pd.to_datetime(data['published'].str['from']).dt.date
data['published_to'] = pd.to_datetime(data['published'].str['to']).dt.date
data.drop(columns=['published'], inplace=True)

In [16]:
def extract_genre_names(x):
    if isinstance(x, list):
        return ",".join([d['name'] for d in x if 'name' in d])
    else:
        return ""  # empty string for missing or invalid

data['genres'] = data['genres'].apply(extract_genre_names)
data['serializations'] = data['serializations'].apply(extract_genre_names)

In [17]:
missing_per_col = data.isna().sum()
print(missing_per_col)

mal_id               0
title                0
type                 0
chapters          2956
volumes           2932
status               0
publishing           0
score             6345
scored_by         6345
rank              3128
popularity           0
members              0
favorites            0
serializations       0
genres               0
published_from     212
published_to      4889
dtype: int64

Xu ly serialization

In [ ]:
label_encoder = LabelEncoder()
data['serializations'] = label_encoder.fit_transform(data['serializations'])

Xu ly gia tri nan vi can de chay model nen da xem xet giu lai cot

In [19]:
avg_score = data['score'].mean()
data['score'] = data['score'].fillna(avg_score)

In [20]:
avg_score_by=data['scored_by'].mean()
data['scored_by']=data['scored_by'].fillna(avg_score_by)

In [21]:
avr_chapter=data['chapters'].mean()
data['chapters']=data['chapters'].fillna(avr_chapter)

In [22]:
avr_volumes=data['volumes'].mean()
data['volumes']=data['volumes'].fillna(avr_volumes)

In [23]:
avr_ranks=data['rank'].mean()
data['rank']=data['rank'].fillna(avr_ranks)

In [24]:
data=data.astype({'chapters':'int64', 'volumes':'int64','scored_by':'int64','score':'int64','rank':'int64'})
data.dtypes

mal_id             int64
title             object
type              object
chapters           int64
volumes            int64
status            object
publishing          bool
score              int64
scored_by          int64
rank               int64
popularity         int64
members            int64
favorites          int64
serializations     int64
genres            object
published_from    object
published_to      object
dtype: object

In [25]:
missing_per_col = data.isna().sum()
print(missing_per_col)

mal_id               0
title                0
type                 0
chapters             0
volumes              0
status               0
publishing           0
score                0
scored_by            0
rank                 0
popularity           0
members              0
favorites            0
serializations       0
genres               0
published_from     212
published_to      4889
dtype: int64

In [26]:
data

,mal_id,title,type,chapters,volumes,status,publishing,score,scored_by,rank,popularity,members,favorites,serializations,genres,published_from,published_to
39083,136355,Hana Akari,Manga,8,1,Finished,False,6,1903,26774,66813,48,0,676,"Boys Love,Drama,Erotica",2014-04-24,2016-05-24
75058,163272,Futarigurashi no Otoriyose Biyori,Manga,23,2,Publishing,True,6,1903,42132,74476,27,0,723,"Gourmet,Slice of Life",2023-04-24,NaT
32496,148128,Kaihatsu Buchou no Himitsu no Oshigoto,Manga,7,1,Finished,False,6,1903,26774,57574,75,0,53,"Boys Love,Erotica",2017-10-06,2018-09-25
16431,41031,Kamakura Deco & Kofu Life,Manga,23,2,Publishing,True,6,1903,39295,37677,223,2,24,"Comedy,Slice of Life",2011-06-18,NaT
59540,17490,First Time I Saw You,Manhwa,23,6,Finished,False,6,1903,24314,67114,48,0,0,Romance,2000-01-01,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76913,107211,Sis x Bro: Siscon Brocon Dairansen,Light Novel,5,1,Finished,False,6,1903,36796,70203,39,1,0,Romance,2016-08-26,NaT
79971,161518,Takanashi-ke no Imouto wa Hanayome ni Naritai!!,Manga,23,2,Publishing,True,6,1903,35402,63708,56,1,711,"Comedy,Romance",2023-08-04,NaT
64605,90431,Boy Meets Boy,Manga,97,9,Finished,False,6,1903,26774,52467,96,0,0,"Boys Love,Erotica",1996-11-01,1998-08-01
34384,186250,Kawaii Hito,One-shot,1,2,Finished,False,6,1903,26774,79870,10,0,229,Hentai,2020-08-12,NaT
51443,107309,Internet Romance: Unmei no Aite wa Gamen no Mu...,Light Novel,23,1,Finished,False,6,1903,36832,74232,28,0,0,Romance,2016-01-29,NaT

In [28]:
data = data.replace({np.nan: None})
data.to_json(
    "manga_data.json",
    orient="records",
    indent=4,
    force_ascii=False
)